apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgres
  title: PostgreSQL Server
  description: Central PostgreSQL Server for relational data
spec:
  type: service
  lifecycle: production
  owner: external
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: document-db
  title: db/document
  description: Stores document base information and their permissions
spec:
  type: database
  owner: acme
  dependsOn:
    - component:postgres
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: keycloak-db
  title: db/document
  description: Database backend for keycloak
spec:
  type: database
  owner: acme
  dependsOn:
    - component:postgres
